platform :ios, '9.0'

target 'Tracking Buses SE' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'GooglePlaces'
  pod 'GooglePlacesAPI'
  pod 'SwiftyJSON'


  # Pods for Maps Direction

end
